# Generated by Django 5.2.16 on 2026-07-23 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, verbose_name='Description du Workflow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='institutions.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name="Nom de l'étape (ex: enter_amount)")),
                ('step_type', models.CharField(choices=[('INPUT', 'Saisie Libre (INPUT)'), ('SELECT', "Sélection d'Option (SELECT)"), ('API_CALL', "Appel d'API Externe (API_CALL)"), ('END', 'Écran de Fin (END)')], max_length=20, verbose_name="Type d'étape")),
                ('prompt_texts', models.JSONField(default=dict, help_text="Format: {'fr': '...', 'en': '...', 'ar': '...'}", verbose_name="Textes d'invite (JSON - fr, en, ar)")),
                ('validation_regex', models.CharField(blank=True, help_text="Laisser vide si aucune validation n'est requise.", max_length=255, verbose_name='Regex de Validation (ex: ^\\d+$)')),
                ('variable_name', models.CharField(blank=True, help_text='Nom sous lequel la valeur saisie sera stockée en session.', max_length=50, verbose_name='Nom de la variable en session (ex: amount)')),
                ('step_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage/exécution")),
                ('next_step_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_steps', to='workflows.workflowstep', verbose_name='Étape Suivante par Défaut')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Étape de Workflow',
                'verbose_name_plural': 'Étapes de Workflows',
                'ordering': ['step_order'],
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='start_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_workflows', to='workflows.workflowstep', verbose_name='Étape Initiale'),
        ),
        migrations.CreateModel(
            name='WorkflowStepBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_value', models.CharField(help_text="La saisie utilisateur qui déclenche cette branche (ex: '1' ou 'oui').", max_length=255, verbose_name='Valeur de condition')),
                ('next_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_sources', to='workflows.workflowstep', verbose_name='Étape Suivante')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='workflows.workflowstep', verbose_name='Étape Source')),
            ],
            options={
                'verbose_name': "Branche d'Étape",
                'verbose_name_plural': "Branches d'Étapes",
                'unique_together': {('step', 'condition_value')},
            },
        ),
    ]
