# Generated by Django 5.2.16 on 2026-07-23 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('session_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name="ID de session Africa's Talking")),
                ('phone_number', models.CharField(max_length=30, verbose_name='Numéro de téléphone')),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', max_length=5, verbose_name='Langue préférée')),
                ('session_data', models.JSONField(default=dict, verbose_name='Données collectées')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminée ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution', verbose_name='Institution active')),
                ('current_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.service', verbose_name='Service actif')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowstep', verbose_name='Étape courante')),
            ],
            options={
                'verbose_name': 'Session USSD',
                'verbose_name_plural': 'Sessions USSD',
            },
        ),
    ]
