# Generated by Django 5.2.16 on 2026-07-23 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'Institution")),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (URL/Routage)')),
                ('ussd_code', models.CharField(max_length=10, unique=True, verbose_name='Code USSD (ex: 1)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('api_base_url', models.URLField(verbose_name="URL de base de l'API")),
                ('encrypted_api_credentials', models.TextField(blank=True, verbose_name='Identifiants API Chiffrés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Service (ex: Transfert)')),
                ('service_code', models.CharField(max_length=10, verbose_name='Code Service (ex: 2)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='institutions.institution', verbose_name='Institution')),
            ],
            options={
                'verbose_name': 'Service Financier',
                'verbose_name_plural': 'Services Financiers',
                'unique_together': {('institution', 'service_code')},
            },
        ),
    ]
